pipeline:
  build:
    image: 192.168.0.11:5000/nemonik/golang:1.11.2
    commands:
      - make lint
      - make test
      - make build
  run:
    image: 192.168.0.11:5000/nemonik/golang:1.11.2
    commands:
      - make run
