kind: pipeline
name: default

steps:
- name: build
  image: 192.168.0.11:5000/nemonik/golang:1.12.1
  commands:
  - make lint
  - make test
  - make build

- name: run
  image: 192.168.0.11:5000/nemonik/golang:1.12.1
  commands:
  - make run
  
  
